#!/usr/bin/env python3
"""Generate evidence/guardrail-bypass-report.md from the live guardrail.

Reads the same BYPASS_ATTEMPTS table the test suite uses and re-executes every
payload against the real validator, so the report cannot drift from the code:
if a control is weakened, the report says so on the next `make evidence`.

It also runs each payload past a deliberately naive regex filter — the kind
these guardrails are usually written with — to quantify what the AST approach
actually buys.
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "mcp-servers"))

from mcp_core.errors import GuardrailViolation  # noqa: E402
from rds_readonly_mcp.guardrails import validate_select  # noqa: E402
from tests.test_guardrail_bypass import ALLOWED, BYPASS_ATTEMPTS  # noqa: E402

# A representative naive filter: "must start with SELECT, must not contain a
# write keyword". This is the shape most hand-rolled SQL guards take.
_STARTS_SELECT = re.compile(r"^\s*select\b", re.I)
_WRITE_WORDS = re.compile(r"\b(insert|update|delete|drop|truncate|alter|create|grant)\b", re.I)


def naive_allows(sql: str) -> bool:
    return bool(_STARTS_SELECT.match(sql)) and not _WRITE_WORDS.search(sql)


def main() -> int:
    lines: list[str] = []
    control_counts: Counter[str] = Counter()
    naive_failures: list[str] = []
    guardrail_failures: list[str] = []

    lines += [
        "# Guardrail bypass report",
        "",
        "Auto-generated by `scripts/bypass_report.py`. Every payload below is",
        "re-executed against the live validator, so this file cannot drift from",
        "the implementation.",
        "",
        "Each attempt is a documented technique for escaping a naive read-only",
        "SQL filter. The column that matters is **Control** — a refusal for the",
        "wrong structural reason is a latent bypass waiting for a schema change,",
        "so the test suite asserts the specific control, not merely that",
        "something raised.",
        "",
        "## Why an AST and not a regex",
        "",
        "The `Naive filter` column applies a representative hand-rolled guard:",
        '"must start with SELECT, must not contain a write keyword". It is the',
        "shape most of these are written in, and it fails **open** — anything the",
        "pattern misses is permitted.",
        "",
        "| # | Attack | Payload | Naive filter | AST guardrail | Control |",
        "|--:|--------|---------|--------------|---------------|---------|",
    ]

    for idx, (label, sql, expected) in enumerate(BYPASS_ATTEMPTS, start=1):
        naive = "**ALLOWED**" if naive_allows(sql) else "refused"
        if naive_allows(sql):
            naive_failures.append(label)
        try:
            validate_select(sql)
            verdict, control = "**NOT REFUSED**", "—"
            guardrail_failures.append(label)
        except GuardrailViolation as exc:
            verdict, control = "refused", f"`{exc.control}`"
            control_counts[exc.control] += 1
            if exc.control != expected:
                guardrail_failures.append(f"{label} (wrong control: {exc.control})")

        payload = sql.replace("|", "\\|").replace("\n", " ")
        payload = payload[:66] + ("…" if len(payload) > 66 else "")
        lines.append(f"| {idx} | {label} | `{payload}` | {naive} | {verdict} | {control} |")

    lines += [
        "",
        "## Statements that must remain permitted",
        "",
        "A guardrail that refuses everything is trivially 'secure' and useless.",
        "These pin the other edge — each must pass, and each is silently given a",
        "`LIMIT`.",
        "",
        "| Query | Result |",
        "|-------|--------|",
    ]
    for label, sql in ALLOWED:
        try:
            out = validate_select(sql)
            ok = "permitted, `LIMIT` enforced" if "LIMIT" in out.upper() else "**no LIMIT**"
            if "LIMIT" not in out.upper():
                guardrail_failures.append(f"{label} (no LIMIT)")
        except GuardrailViolation as exc:
            ok = f"**WRONGLY REFUSED** ({exc.control})"
            guardrail_failures.append(f"{label} (false positive)")
        lines.append(f"| {label} | {ok} |")

    total = len(BYPASS_ATTEMPTS)
    lines += [
        "",
        "## Summary",
        "",
        f"- Attack payloads tested: **{total}**",
        f"- Refused by the AST guardrail: **{total - len(guardrail_failures)}**",
        f"- Would have passed the naive regex filter: **{len(naive_failures)}** "
        f"({100 * len(naive_failures) // total}%)",
        "",
        "### Refusals by control",
        "",
        "| Control | Count | What it catches |",
        "|---------|------:|-----------------|",
    ]
    descriptions = {
        "read-only": "any mutating node anywhere in the parse tree",
        "single-statement": "stacked statements (`SELECT 1; DROP …`)",
        "function-denylist": "filesystem, network, and DoS functions by resolved name",
        "relation-allowlist": "reads against tables outside the permitted set",
        "no-locking": "`FOR UPDATE` / `FOR SHARE` row locks",
        "sql-parse": "input that will not parse — never executed to find out",
    }
    for control, count in control_counts.most_common():
        lines.append(f"| `{control}` | {count} | {descriptions.get(control, '')} |")

    lines += [
        "",
        "### Payloads the naive filter would have let through",
        "",
    ]
    lines += [f"- {name}" for name in naive_failures] or ["- (none)"]

    lines += [
        "",
        "## Defence in depth",
        "",
        "This layer is the second of three, and it is not the last:",
        "",
        "1. `mcp_core` — protocol shape and tool allowlist",
        "2. `guardrails.py` — this report",
        "3. the `mcp_readonly` database role — see `db-privilege-proof.txt`",
        "",
        "Layer 3 exists because layer 2 can have bugs. Every payload above is",
        "*also* refused by PostgreSQL itself, with the application entirely out",
        "of the picture. The guardrail's job is a fast, legible refusal the model",
        "can act on; the grant is what makes the refusal true.",
        "",
    ]

    if guardrail_failures:
        lines += ["## ⚠️ FAILURES", ""] + [f"- {f}" for f in guardrail_failures] + [""]

    out_path = REPO_ROOT / "evidence" / "guardrail-bypass-report.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"wrote {out_path.relative_to(REPO_ROOT)}")
    print(f"  {total} payloads · {len(naive_failures)} would pass a naive regex · "
          f"{len(guardrail_failures)} guardrail failures")
    return 1 if guardrail_failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
